Repository hawks-atlanta/gateway-java, pull requests merged in 2023-10, with the labels that each got.

#55 chore: Improve cli client
  .gitignore
  cli-client/cli.py
  cli-client/handlers.py
  cli-client/simple.py
  soap-python-client.py
Labels: enhancement

#57 feat: file check ready
  app/src/main/java/gateway/controller/CtrlAccountRegister.java
  app/src/main/java/gateway/controller/CtrlAuthLogin.java
  app/src/main/java/gateway/controller/CtrlFileCheck.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/test/java/gateway/ITFileIO.java
  cli-client/simple.py
  format.sh
Labels: enhancement, feature

#59 chore: Rename soap endpoint
  app/src/main/java/gateway/App.java
  cli-client/handlers.py
  cli-client/simple.py
Labels: cd

#56 feat: challenge endpoint
  app/src/main/java/gateway/controller/CtrlAuthRefresh.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/request/Authorization.java
  app/src/test/java/gateway/ITServiceAuth.java
  cli-client/cli.py
  cli-client/handlers.py
  cli-client/simple.py
  docker-compose.yml
  docs/spec.openapi.yml
Labels: feature

#63 Fix: Delete Unnecesary resFileNew
  app/src/main/java/gateway/controller/CtrlAuthLogin.java
Labels: fix

#60 test: Add tests for register method
  app/src/main/java/gateway/controller/CtrlAccountRegister.java
  app/src/test/java/gateway/ITServiceAuth.java
Labels: enhancement

#61 Feat: share file feature
  app/src/main/java/gateway/controller/CtrlShareFile.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/request/ReqShareFile.java
  app/src/test/java/gateway/ITShareFile.java
  docker-compose.yml
Labels: feature

#66 chore(release): v0.0.30
  CHANGELOG.md
  app/src/main/java/gateway/App.java
  app/src/main/java/gateway/controller/CtrlAccountRegister.java
  app/src/main/java/gateway/controller/CtrlAuthLogin.java
  app/src/main/java/gateway/controller/CtrlAuthRefresh.java
  app/src/main/java/gateway/controller/CtrlShareFile.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/request/Authorization.java
  app/src/main/java/gateway/soap/request/ReqShareFile.java
  app/src/test/java/gateway/ITServiceAuth.java
  app/src/test/java/gateway/ITShareFile.java
  cli-client/cli.py
  cli-client/handlers.py
  cli-client/simple.py
  docker-compose.yml
  docs/spec.openapi.yml
  package-lock.json
  package.json
Labels: ci

#69 feat: File rename
  app/src/main/java/gateway/controller/CtrlFileRename.java
  app/src/main/java/gateway/soap/Service.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/request/ReqFileRename.java
  app/src/main/java/gateway/soap/request/ReqRenameFile.java
  app/src/test/java/gateway/ITFileManagment.java
  cli-client/simple.py
  docs/spec.openapi.yml
Labels: documentation, feature

#71 feat: create new directory
  app/src/main/java/gateway/controller/CtrlFileNewDir.java
  app/src/main/java/gateway/controller/CtrlFileUpload.java
  app/src/main/java/gateway/services/ServiceMetadata.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/request/ReqFileMove.java
  app/src/main/java/gateway/soap/request/ReqFileNewDir.java
  app/src/test/java/gateway/ITFileIO.java
  app/src/test/java/gateway/ITFileManagment.java
  app/src/test/java/gateway/ITShareFile.java
  cli-client/simple.py
  docs/spec.openapi.yml
Labels: documentation, feature

#72 chore(release): v0.0.35
  CHANGELOG.md
  CLI.md
  README.md
  app/src/main/java/gateway/controller/CtrlFileNewDir.java
  app/src/main/java/gateway/controller/CtrlFileRename.java
  app/src/main/java/gateway/controller/CtrlFileUpload.java
  app/src/main/java/gateway/controller/CtrlUpdatePassword.java
  app/src/main/java/gateway/services/ServiceMetadata.java
  app/src/main/java/gateway/soap/Service.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/request/ReqAccPassword.java
  app/src/main/java/gateway/soap/request/ReqFileMove.java
  app/src/main/java/gateway/soap/request/ReqFileNewDir.java
  app/src/main/java/gateway/soap/request/ReqFileRename.java
  app/src/main/java/gateway/soap/request/ReqRenameFile.java
  app/src/test/java/gateway/ITFileIO.java
  app/src/test/java/gateway/ITFileManagment.java
  app/src/test/java/gateway/ITShareFile.java
  app/src/test/java/gateway/ITUpdatePassword.java
  cli-client/simple.py
  docs/spec.openapi.yml
  package-lock.json
  package.json
Labels: ci, feature

#73 fix: Update field validation
  app/src/main/java/gateway/controller/CtrlFileUpload.java
  app/src/main/java/gateway/services/UtilValidator.java
  app/src/main/java/gateway/soap/request/Credentials.java
  app/src/main/java/gateway/soap/request/ReqAccPassword.java
  app/src/main/java/gateway/soap/request/ReqFileDelete.java
  app/src/main/java/gateway/soap/request/ReqFileMove.java
  app/src/main/java/gateway/soap/request/ReqFileNewDir.java
  app/src/main/java/gateway/soap/request/ReqFileRename.java
  app/src/main/java/gateway/soap/request/ReqFileUpload.java
  app/src/main/java/gateway/soap/request/ReqShareFile.java
  app/src/main/java/gateway/soap/request/ReqShareRemove.java
Labels: enhancement

#76 feat: Get file by UUID
  app/src/main/java/gateway/controller/CtrlFileGet.java
  app/src/main/java/gateway/services/ServiceMetadata.java
  app/src/main/java/gateway/soap/Service.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/response/File.java
  app/src/main/java/gateway/soap/response/ResFileGet.java
  app/src/test/java/gateway/ITFileManagment.java
  cli-client/cli.py
  cli-client/handlers.py
  docs/spec.openapi.yml
Labels: feature

#77 feat: File move
  app/src/main/java/gateway/controller/CtrlFileMove.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/test/java/gateway/ITFileManagement.java
  cli-client/cli.py
  cli-client/handlers.py
  docker-compose.yml
Labels: feature

#74 feat: List Files
  app/src/main/java/gateway/controller/CtrlFileList.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/test/java/gateway/ITFileList.java
  docs/spec.openapi.yml
Labels: feature

#78 chore(release): v0.0.40
  CHANGELOG.md
  app/src/main/java/gateway/controller/CtrlFileGet.java
  app/src/main/java/gateway/controller/CtrlFileList.java
  app/src/main/java/gateway/controller/CtrlFileMove.java
  app/src/main/java/gateway/controller/CtrlFileUpload.java
  app/src/main/java/gateway/services/ServiceMetadata.java
  app/src/main/java/gateway/services/UtilValidator.java
  app/src/main/java/gateway/soap/Service.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/request/Credentials.java
  app/src/main/java/gateway/soap/request/ReqAccPassword.java
  app/src/main/java/gateway/soap/request/ReqFileDelete.java
  app/src/main/java/gateway/soap/request/ReqFileMove.java
  app/src/main/java/gateway/soap/request/ReqFileNewDir.java
  app/src/main/java/gateway/soap/request/ReqFileRename.java
  app/src/main/java/gateway/soap/request/ReqFileUpload.java
  app/src/main/java/gateway/soap/request/ReqShareFile.java
  app/src/main/java/gateway/soap/request/ReqShareRemove.java
  app/src/main/java/gateway/soap/response/File.java
  app/src/main/java/gateway/soap/response/ResFileGet.java
  app/src/test/java/gateway/ITFileList.java
  app/src/test/java/gateway/ITFileManagement.java
  app/src/test/java/gateway/ITFileManagment.java
  cli-client/cli.py
  cli-client/handlers.py
  docker-compose.yml
  docs/spec.openapi.yml
  package-lock.json
  package.json
Labels: ci

#79 Feat: List Shared With Who
  app/src/main/java/gateway/controller/CtrlShareListWithWho.java
  app/src/main/java/gateway/services/ServiceAuth.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/test/java/gateway/ITFileList.java
  app/src/test/java/gateway/ITFileManagement.java
  app/src/test/java/gateway/ITServiceAuth.java
  app/src/test/java/gateway/ITShareFile.java
  app/src/test/java/gateway/ITShareListWhitWho.java
  app/src/test/java/gateway/testutils/TestUtilAuth.java
Labels: feature

#81 chore(release): v0.0.42
  CHANGELOG.md
  app/src/main/java/gateway/controller/CtrlShareListWithWho.java
  app/src/main/java/gateway/services/ServiceAuth.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/test/java/gateway/ITFileList.java
  app/src/test/java/gateway/ITFileManagement.java
  app/src/test/java/gateway/ITServiceAuth.java
  app/src/test/java/gateway/ITShareFile.java
  app/src/test/java/gateway/ITShareListWhitWho.java
  app/src/test/java/gateway/testutils/TestUtilAuth.java
  package-lock.json
  package.json
Labels: ci

#82 Feat: list shared
  app/src/main/java/gateway/controller/CtrlFileList.java
  app/src/main/java/gateway/controller/CtrlShareList.java
  app/src/main/java/gateway/services/UtilsFiles.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/response/ResShareList.java
  app/src/main/java/gateway/soap/response/SharedFile.java
  app/src/test/java/gateway/ITShareFile.java
  app/src/test/java/gateway/ITShareListWhitWho.java
  app/src/test/java/gateway/ITShareManagement.java
  app/src/test/java/gateway/testutils/TestUtilShare.java
  cli-client/cli.py
  cli-client/handlers.py
Labels: feature

#83 chore(release): v0.0.44
  CHANGELOG.md
  app/src/main/java/gateway/controller/CtrlFileList.java
  app/src/main/java/gateway/controller/CtrlShareList.java
  app/src/main/java/gateway/services/UtilsFiles.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/response/ResShareList.java
  app/src/main/java/gateway/soap/response/SharedFile.java
  app/src/test/java/gateway/ITShareFile.java
  app/src/test/java/gateway/ITShareListWhitWho.java
  app/src/test/java/gateway/ITShareManagement.java
  app/src/test/java/gateway/testutils/TestUtilShare.java
  cli-client/cli.py
  cli-client/handlers.py
  package-lock.json
  package.json
Labels: ci

#85 chore(release): v0.0.46
  CHANGELOG.md
  README.md
  app/src/main/java/gateway/controller/CtrlFileDelete.java
  app/src/main/java/gateway/soap/request/ReqFileDelete.java
  app/src/test/java/gateway/TIFileDelete.java
  docs/spec.openapi.yml
  package-lock.json
  package.json
Labels: cd

#88 chore(release) v0.0.48
  CHANGELOG.md
  app/src/main/java/gateway/soap/ServiceImp.java
  package-lock.json
  package.json
Labels: ci

#86 feat: unshare file
  app/src/main/java/gateway/controller/CtrlUnshareFile.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/request/ReqShareRemove.java
  app/src/test/java/gateway/ITShareManagement.java
  app/src/test/java/gateway/testutils/TestUtilShare.java
Labels: feature

#89 chore(release): v0.0.50
  CHANGELOG.md
  app/src/main/java/gateway/controller/CtrlUnshareFile.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/request/ReqShareRemove.java
  app/src/test/java/gateway/ITShareManagement.java
  app/src/test/java/gateway/testutils/TestUtilShare.java
  package-lock.json
  package.json
Labels: ci
