Repository hawks-atlanta/gateway-java, pull requests merged in 2023-09, with the labels that each got.

#15 feat: SOAP service definition
  app/src/main/java/gateway/App.java
  app/src/main/java/gateway/soap/SampleService.java
  app/src/main/java/gateway/soap/SampleServiceImp.java
  app/src/main/java/gateway/soap/Service.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/request/Authorization.java
  app/src/main/java/gateway/soap/request/CreateDirectoryReq.java
  app/src/main/java/gateway/soap/request/CreateFileReq.java
  app/src/main/java/gateway/soap/request/Credentials.java
  app/src/main/java/gateway/soap/request/DeleteFileReq.java
  app/src/main/java/gateway/soap/request/DownloadFileReq.java
  app/src/main/java/gateway/soap/request/ListFileReq.java
  app/src/main/java/gateway/soap/request/MoveFileReq.java
  app/src/main/java/gateway/soap/request/Operation.java
  app/src/main/java/gateway/soap/request/ShareWithReq.java
  app/src/main/java/gateway/soap/request/SharedWithWhoReq.java
  app/src/main/java/gateway/soap/request/UnShareWithReq.java
  app/src/main/java/gateway/soap/request/UpdatePasswordReq.java
  app/src/main/java/gateway/soap/response/File.java
  app/src/main/java/gateway/soap/response/FileContents.java
  app/src/main/java/gateway/soap/response/SharedFile.java
  app/src/main/java/gateway/soap/response/StatusRes.java
  app/src/main/java/gateway/soap/response/User.java
  soap-python-client.py
Labels: documentation

#19 fox: SOAP share response types
  app/src/main/java/gateway/soap/request/ShareWithReq.java
  app/src/main/java/gateway/soap/request/UnShareWithReq.java
  app/src/main/java/gateway/soap/response/SharedFile.java
Labels: documentation

#36 feat: Normalize status response format
  app/src/main/java/gateway/soap/Service.java
  app/src/main/java/gateway/soap/ServiceImp.java
  app/src/main/java/gateway/soap/response/DownloadFileRes.java
  app/src/main/java/gateway/soap/response/FileContents.java
  app/src/main/java/gateway/soap/response/ListFileRes.java
  app/src/main/java/gateway/soap/response/ListSharedWithMeRes.java
  app/src/main/java/gateway/soap/response/SessionRes.java
  app/src/main/java/gateway/soap/response/SharedWithWhoRes.java
  app/src/main/java/gateway/soap/response/StatusRes.java
  app/src/main/java/gateway/soap/response/User.java
Labels: enhancement, feature

#38 feat: Config from env vars
  CLI.md
  Dockerfile
  README.md
  app/src/main/java/gateway/App.java
  app/src/main/java/gateway/config/Config.java
  docker-compose.yaml
Labels: enhancement

#35 feat: adding register implementation and some changes in .gitignore
  .gitignore
  app/src/main/java/gateway/config/Config.java
  app/src/main/java/gateway/soap/ServiceImp.java
  soap-python-client.py
Labels: feature

#40 Feat login
  app/src/main/java/gateway/soap/ServiceImp.java
  soap-python-client.py
Labels: feature
